Repository MSU-CSE491/cse_491_fall_2023, pull requests merged in 2023-10, with the labels that each got.

#28 Removed undefined behavior from WorldGrid
  source/core/WorldGrid.hpp
Labels: Goal: Bug Fix, Merge: READY, Topic: Core Program

#30 Ignores Executable files
  .gitignore
Labels: Goal: Bug Fix, Merge: READY

#34 Adjusted properties to be of any type
  source/Interfaces/TrashInterface.hpp
  source/core/Entity.hpp
  source/simple_main.cpp
Labels: Goal: New Feature, Merge: READY, Topic: API
